ClientEvents.lang('en_us', event => {
    event.add('block.pneumaticcraft.ethanol', "Ethanol")
    event.add('ritual.spongefactory.craft_vacuum_pump.started', "Start converting the encased fan into a vacuum pump.")
    event.add('ritual.spongefactory.craft_vacuum_pump.finished', "Successfully converted a encased fan into a vacuum pump")
    event.add('ritual.spongefactory.craft_printed_circuit_board.started', "Start soldering circuit components to the Unassembled PCB.")
    event.add('ritual.spongefactory.craft_printed_circuit_board.finished', "Successfully soldered circuit components to the Unassembled PCB.")
    event.add('chapter.spongefactory.welcome.multiblock.title', "Multiblock Structure")
    event.add('chapter.spongefactory.welcome.multiblock.subtitle', "There are some structures in Schematic Table, which can be downloaded to Empty Schematic. The name of the structure is usually the abbreviation of Mod + name")
    event.add('chapter.spongefactory.welcome.quests.title',"Quests")
    event.add('chapter.spongefactory.welcome.quests.subtitle',"Generally speaking, all quests are arranged in order from left to right according to progress. In most cases, you can know the direction of the quest without looking at the arrows.")
})
ClientEvents.lang('zh_cn', event => {
    event.add('block.pneumaticcraft.ethanol', "乙醇")
    event.add('ritual.spongefactory.craft_vacuum_pump.started', "开始将鼓风机转化为真空泵。")
    event.add('ritual.spongefactory.craft_vacuum_pump.finished', "成功将鼓风机转化为真空泵。")
    event.add('ritual.spongefactory.craft_printed_circuit_board.started', "开始将电路元件焊接到未组装的印刷电路板。")
    event.add('ritual.spongefactory.craft_printed_circuit_board.finished', "成功将电路元件焊接到未组装的印刷电路板。")
    event.add('chapter.spongefactory.welcome.multiblock.title', "多方块结构")
    event.add('chapter.spongefactory.welcome.multiblock.subtitle', "蓝图桌里有一些结构，可以下载到空白蓝图。 结构名通常是Mod的缩写+名称")
    event.add('chapter.spongefactory.welcome.quests.title',"任务")
    event.add('chapter.spongefactory.welcome.quests.subtitle',"一般来说所有任务的顺序按照进度从左到右排，大多数情况下不需要看箭头就能知道任务的走向。")
})