ClientEvents.lang('en_us', event => {
    event.add('block.pneumaticcraft.ethanol', "Ethanol")
    event.add('block.immersivepetroleum.benzene_fluid_block', "Benzene")
    event.add('ritual.spongefactory.craft_vacuum_pump.started', "Start converting the Encased Fan into a Vacuum Pump.")
    event.add('ritual.spongefactory.craft_vacuum_pump.finished', "Successfully converted a Encased Fan into a Vacuum Pump")
    event.add('ritual.spongefactory.craft_printed_circuit_board.started', "Start soldering Circuit Components to the Unassembled PCB.")
    event.add('ritual.spongefactory.craft_printed_circuit_board.finished', "Successfully soldered Circuit Components to the Unassembled PCB.")
    event.add('ritual.spongefactory.craft_fortress_finder.started', "Start converting the Infused Ender Pearl into an Eye of the Blaze.")
    event.add('ritual.spongefactory.craft_fortress_finder.finished', "Successfully converted a Infused Ender Pearl into an Eye of the Blaze.")
    event.add('ritual.spongefactory.craft_space_link_eye.started', "Start linking high-dimensional space.")
    event.add('ritual.spongefactory.craft_space_link_eye.finished', "Linking high-dimensional space successfully.")

    event.add('electric_age.chapter.spongefactory.chapter_6.title', 'Chapter 6')
    event.add('electric_age.chapter.spongefactory.chapter_7.title', 'Chapter 7')
    event.add('electric_age.chapter.spongefactory.chapter_8.title', 'Chapter 8')
    event.add('electric_age.chapter.spongefactory.chapter_9.title', 'Chapter 9')
    event.add('chapter.spongefactory.welcome.multiblock.title', "Multiblock Structure")
    event.add('chapter.spongefactory.welcome.multiblock.subtitle', "There are some structures in Schematic Table, which can be downloaded to Empty Schematic. The name of the structure is usually the abbreviation of Mod + name")
    event.add('chapter.spongefactory.welcome.quests.title',"Quests")
    event.add('chapter.spongefactory.welcome.quests.subtitle',"Generally speaking, all quests are arranged in order from left to right according to progress. In most cases, you can know the direction of the quest without looking at the arrows.")
    event.add('chapter.spongefactory.welcome.jecharacters.title','For Players Using English')
    event.add('chapter.spongefactory.welcome.jecharacters.subtitle','This Modpack comes with Jecharacters mod pre-installed. Players who prefer playing in English are advised to remove it.')
    event.add('questGroup.spongefactory.tech_tree','Tech Tree')
    event.add('tech_tree.spongefactory.generators.title','Generators')
})
ClientEvents.lang('zh_cn', event => {
    event.add('block.pneumaticcraft.ethanol', "乙醇")
    event.add('block.immersivepetroleum.benzene_fluid_block', "苯")
    event.add('ritual.spongefactory.craft_vacuum_pump.started', "开始将鼓风机转化为真空泵。")
    event.add('ritual.spongefactory.craft_vacuum_pump.finished', "成功将鼓风机转化为真空泵。")
    event.add('ritual.spongefactory.craft_printed_circuit_board.started', "开始将电路元件焊接到未组装的印刷电路板。")
    event.add('ritual.spongefactory.craft_printed_circuit_board.finished', "成功将电路元件焊接到未组装的印刷电路板。")
    event.add('ritual.spongefactory.craft_fortress_finder.started', "开始将注能末影珍珠转换为烈焰之眼。")
    event.add('ritual.spongefactory.craft_fortress_finder.finished', "成功将注能末影珍珠转换为烈焰之眼。")
    event.add('ritual.spongefactory.craft_space_link_eye.started', "开始链接高维空间。")
    event.add('ritual.spongefactory.craft_space_link_eye.finished', "链接高维空间成功。")

    event.add('electric_age.chapter.spongefactory.chapter_6.title', '第六章')
    event.add('electric_age.chapter.spongefactory.chapter_7.title', '第七章')
    event.add('electric_age.chapter.spongefactory.chapter_8.title', '第八章')
    event.add('electric_age.chapter.spongefactory.chapter_9.title', '第九章')
    event.add('chapter.spongefactory.welcome.multiblock.title', "多方块结构")
    event.add('chapter.spongefactory.welcome.multiblock.subtitle', "蓝图桌里有一些结构，可以下载到空白蓝图。 结构名通常是Mod的缩写+名称")
    event.add('chapter.spongefactory.welcome.quests.title',"任务")
    event.add('chapter.spongefactory.welcome.quests.subtitle',"一般来说所有任务的顺序按照进度从左到右排，大多数情况下不需要看箭头就能知道任务的走向。")
    event.add('chapter.spongefactory.welcome.jecharacters.title','致使用英语游玩的玩家')
    event.add('chapter.spongefactory.welcome.jecharacters.subtitle','本整合包默认安装了Jecharacters，建议所有使用英语游玩的玩家删除此mod。')
    event.add('questGroup.spongefactory.tech_tree','科技树')
    event.add('tech_tree.spongefactory.generators.title','发电机')
})